version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.11.71@sha256:36b79b6113324b1977c71a643fbf86a00959c770a8413c8808ac5c66b74c2a7d
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
